/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Software_Eng_Assignment1_Part_B;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
